config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :posts do 
    collection do
      get :top
      get :main
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :notifications, :only => [:index, :destroy]
  root 'posts#top'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         mount_uploader :image, ImageUploader

  has_many :posts
  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
        @notifications = Notification.where(visited_id: current_user.id)
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
        if @user.id == current_user.id
        @msg ="他のユーザーとDMしてみよう！"
        else
        @currentUserEntry.each do |cu|
            @userEntry.each do |u|
            if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
            end
            end
        end

        if @isRoom != true
            @room = Room.new
            @entry = Entry.new
        end

        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<header class="header">
    <div class="header__inner">
        <div class="logo">
            <span class="logo__w">W</span>
            <span class="logo__community">community</span>
        </div>
        <nav class="header__nav">
            <ul class="header__ul">
                <li class="header__li">
                    <%= link_to 'Home', main_posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'OutGoing', posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'MyPage', user_path(current_user.id)%> 
                </li>
                <li class="header__li">
                    <%= link_to (rooms_path) do %>
                        DM<i class="far fa-comment-dots"></i><span class="noti_count"><%= @notifications.count %></span>
                    <% end %>
                </li>
                <li class="header__li">
                    <%= link_to 'notifications', notifications_path %>
                </li>
                <li class="header__li">
                    <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
                </li>
            </ul>
        </nav>
    </div>
</header>

<div class="user_show_top">
    <div class="user_show_bgi"></div>
    <%= image_tag @user.image_url, class:"user_show_img" if @user.image? %>
    <div class="user_show_first">
        <p class="user_show_name"><%= @user.name %></p>
        <% if current_user.id == @user.id %>
            <%= link_to "プロフィールを編集する", edit_user_registration_path %>
        <% end %>
        <p class="user_show_profile"><%= @user.profile %></p>
    </div>
    <div class="user_show_dm">
        <% if @user.id == current_user.id %>
            <%= @msg %>
        <% else %>
            <% if @isRoom == true %>
                <%= button_to 'DMへ', room_path(@roomId), class:"btn btn-outline-secondary" %>
            <% else %>
                <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e|%>
                        <% e.hidden_field :user_id, value: @user.id %>
                    <% end %>
                <%= f.submit "メッセージをおくる"%>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

<div class="user_show_center">
    <div class="user_show_detail">
        <p>メールアドレス : <%= @user.email %></p>
        <p>お住まいの地域 : <%= @user.address %></p>
        <p>エンジニア : <%= @user.job %></p>
        <p>種類 : <%= @user.genre %></p>
    </div>
</div>


<div class="user_show_bottom">

    <div class="user_show_index">
        <h2>ユーザーの投稿一覧</h2>
        <% @user.posts.each do |p| %>
            <%= p.user.name %>
            <%= p.theme %>
        <% end %>
    </div>

    <div class="user_show_like">
        <h2>ユーザーがいいねした投稿一覧</h2>
        <% @user.liked_posts.each do |p| %>
            <%= p.user.name %>
            <%= p.theme %>
        <% end %>
    </div>

</div>