config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :posts do 
    collection do
      get :top
      get :main
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :notifications, :only => [:index, :destroy]
  root 'posts#top'
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :notifications, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @users = User.where.not(id: current_user.id)

    @anotherEntries = Entry.where(room_id: myRoomIds, user_id: @users.ids)
  end

  def show
    @room = Room.find(params[:id])
      if Entry.where(user_id: current_user.id, room_id: @room.id).present?
        @messages = @room.messages.all
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
      
  end

  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="dmlist">
    <div class="dmlist__link">
        <%= link_to "＜ メインページへ", main_posts_path %>
    </div>

    <h2><%= current_user.name %>のDM一覧</h2>
    <div class="dmlist__main">
        <% @anotherEntries.each do |e| %>
            <hr>
            <div class="dmlist__index">
                <%= image_tag e.user.image_url, class:"dmlist__img" if e.user.image? %>
                <%= link_to e.user.name, room_path(e.room_id) %>（<%= Notification.where(visitor_id: e.user.id).count %>）
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="dmroom">
    <div class="dmroom__link">
        <%= link_to "＜ DM一覧に戻る", rooms_path %>
        <%= link_to "メインページに戻る", main_posts_path %>
    </div>
    <%
=begin%>
 <div class="dmroom__user-in">
        <% @entries.each do |e| %>
            <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.name%></a></strong></h3>
        <% end %>
        <p>2人のDM❤️</p>
    </div> 
<%
=end%>

    <div class="dmroom__main">
        <div class="dmroom__message">
            <% @messages.each do |m| %>
                <% if m.user_id == current_user.id %>
                    <div class="current_user">
                        <small class="current_user"><%= m.user.name %></small>
                        <strong class="current_user"><%= m.body %></strong>
                    </div>
                <% else %>
                    <div class="visited_user">
                        <strong class="visited_user"><%= m.body %></strong>
                        <small class="visited_user"><%= m.user.name %>さん</small>
                    </div>
                <% end %>

                <% if m.user_id != current_user.id %>
                    <% if m.notifications.exists? %>
                        <%= link_to '既読にする', notification_path(m.id), method: :delete, class: "dmroom__read"%>
                    <% else %>
                        <p class="dmroom__read">既読</p>
                    <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="dmroom__form">
            <%= form_for @message do |f| %>
                <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
                <%= f.hidden_field :room_id, :value => @room.id %>
                <%= f.submit "送信する" %>
            <% end %>
        </div>
    </div>
</div>