config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/index'
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :posts do 
    collection do
      get :top
      get :main
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :notifications, :only => [:index, :destroy]
  root 'posts#top'
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :top
  before_action :set_q, only: [:main, :search]

  def index
    @posts = Post.all
    @notifications = Notification.where(visited_id: current_user.id)
  end

  def main
    if params[:q] == nil
      @users = User.all
    elsif params[:q] == ""
      @users = User.all
    else
      @users = @q.result
    end

    @notifications = Notification.where(visited_id: current_user.id)
  end

  def new
    @post = Post.new
    @notifications = Notification.where(visited_id: current_user.id)
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
      redirect_to posts_path
    else
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
    @notifications = Notification.where(visited_id: current_user.id)
  end

  def edit
    @post = Post.find(paraml[:id])
  end
  
  def update
    post = Post.find(params[:id])
    if post.save
      redirect_to posts_path
    else
      redirect_to new_post_path
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to action: :index
  end

  def search
    @results = @q.result
  end

  private
  def post_params
    params.require(:post).permit(:theme, :content, :image, :link)
  end
  def set_q
    @q = User.ransack(params[:q])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<header class="header">
    <div class="header__inner">
        <div class="logo">
            <span class="logo__w">W</span>
            <span class="logo__community">community</span>
        </div>
        <nav class="header__nav">
            <ul class="header__ul">
                <li class="header__li">
                    <%= link_to 'Home', main_posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'OutGoing', posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'MyPage', user_path(current_user.id)%> 
                </li>
                <li class="header__li">
                    <%= link_to (rooms_path) do %>
                        DM<i class="far fa-comment-dots"></i><span class="noti_count"><%= @notifications.count %></span>
                    <% end %>
                </li>
                <li class="header__li">
                    <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
                </li>
            </ul>
        </nav>
    </div>
</header>

<div class="list">
    <div class="list__head">
        <h2>投稿一覧</h2>
        <%= link_to "新規投稿", new_post_path %>
    </div>
    <% @posts.each do |p| %>
        <div class="list__main">
            <div class="list__user">
                <a href="/users/<%= p.user.id %>"><%= p.user.name %></a>
                <%= link_to "削除する", post_path(p.id), method: :delete %>
            </div>
            テーマ：<%= p.theme %>
            <%= link_to "詳細へ", post_path(p.id) %>
        </div>
        
        <% if user_signed_in? %>
            <% if current_user.already_liked?(p) %>
                <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= p.likes.count %>
                <% end %>
            <% else %>
                <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
                    <i class="fas fa-heart"></i><%= p.likes.count %>
                <% end %>
            <% end %>
            <% else %>
                <i class="fas fa-heart"></i><%= p.likes.count %>
        <% end %>
    <% end %>
</div>
                

app/views/posts/new.html.erb
<header class="header">
    <div class="header__inner">
        <div class="logo">
            <span class="logo__w">W</span>
            <span class="logo__community">community</span>
        </div>
        <nav class="header__nav">
            <ul class="header__ul">
                <li class="header__li">
                    <%= link_to 'Home', main_posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'OutGoing', posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'MyPage', user_path(current_user.id)%> 
                </li>
                <li class="header__li">
                    <%= link_to (rooms_path) do %>
                        DM<i class="far fa-comment-dots"></i><span class="noti_count"><%= @notifications.count %></span>
                    <% end %>
                </li>
                <li class="header__li">
                    <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
                </li>
            </ul>
        </nav>
    </div>
</header>
<div class="new">
    <div class="new__link">
        <%= link_to '＜ 投稿一覧へ', posts_path %>
    </div>
    <h2>新規投稿</h2>
    <div class="new__main">
        <%= form_with model:@post do |f| %>
            <div class="field">
                <%= f.label :theme %>
                <%= f.text_area :theme, class: "new__area" %>
            </div>
            <%= f.submit :投稿, class: "new__btn" %>
        <% end %>
    </div>
</div>

app/views/posts/search.html.erb
<h2>検索結果</h2>
<% @results.each do |s| %>
    <div class="result">
        名前：<%= s.name %>
    </div>
<% end %>

<%= link_to "メインページへ", main_posts_path %>

app/views/posts/show.html.erb
<header class="header">
    <div class="header__inner">
        <div class="logo">
            <span class="logo__w">W</span>
            <span class="logo__community">community</span>
        </div>
        <nav class="header__nav">
            <ul class="header__ul">
                <li class="header__li">
                    <%= link_to 'Home', main_posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'OutGoing', posts_path %>
                </li>
                <li class="header__li">
                    <%= link_to 'MyPage', user_path(current_user.id)%> 
                </li>
                <li class="header__li">
                    <%= link_to (rooms_path) do %>
                        DM<i class="far fa-comment-dots"></i><span class="noti_count"><%= @notifications.count %></span>
                    <% end %>
                </li>
                <li class="header__li">
                    <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
                </li>
            </ul>
        </nav>
    </div>
</header>

<div class="postshow">
    <div class="postshow__link">
        <%= link_to '＜ 投稿一覧へ', posts_path %>
    </div>
    <h3>投稿詳細</h3>
    <div class="postshow__main">
        <%= image_tag @post.user.image_url, class:"dmlist__img" if @post.user.image? %>
        <a href="/users/<%= @post.user.id %>"><%= @post.user.name %></a>
        <hr>
        <p><%= @post.theme %></p>
    </div>

    <% if user_signed_in? %>
        <% if current_user.already_liked?(@post) %>
            <%= link_to post_like_path(@post), method: :delete do %>
                <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(@post), method: :post do %>
                <i class="fas fa-heart"></i><%= @post.likes.count %>
            <% end %>
        <% end %>
    <% else %>
    <i class="fas fa-heart"></i><%= @post.likes.count %>
    <% end %>
    <div class="postshow__good">
        <div class="comment-wrapper">
            <p>コメント一覧</p>
            <% @comments.each do |c| %>
                <div>
                <%= image_tag c.user.image_url, class:"dmlist__img" if c.user.image? %>
                <%= c.user.name unless c.user.blank? %>
                <br>
                <%= c.content %>
                </div>
                <br>
            <% end %>

            <% if user_signed_in? %>
                <%= form_with(model: [@post, @comment], local: true) do |f| %>
                <%= f.text_area :content %>
                <%= button_tag type: "submit" do %>
                    <i class="far fa-comments"></i> コメント
                <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="good-count">
        <p>いいねしたユーザー</p>
            <% @post.liked_users.each do |user| %>
                <li class="good-count__list">
                    <%= image_tag user.image_url, class:"dmlist__img" if user.image? %>
                    <%= user.name %>
                </li>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/top.html.erb
<%= stylesheet_link_tag 'header', :media => "all" %>
<%= stylesheet_link_tag 'footer', :media => "all" %>
<%= stylesheet_link_tag 'top', :media => "all" %>

<header class="header">
    <div class="header__inner">
        <div class="logo">
            <span class="logo__w">W</span>
            <span class="logo__community">community</span>
        </div>
        <nav class="header__nav">
            <ul class="header__ul">
                <li class="header__li">
                    <%= link_to "Main", main_posts_path %>
                </li>
                <li class="header__li"><a href="#">Contact</a></li>
                <li class="header__li">
                    <%= link_to "LogIn", main_posts_path %>
                </li>
            </ul>
        </nav>
    </div>
</header>


<div class="wrapper">
    <div class="top">
        <div class="top__main">
            <img src="/assets/top.png" alt="top" />
            <h1>女性エンジニアと<br>繋がる</h1>
            <p>女性エンジニアやエンジニアを目指す女性が繋がるサービスです。</p>
            <div class="top__btn">
                <%= button_to "新規登録（無料）", new_user_registration_path, {class: "btn float", method: :get} %>
                <%= link_to "ログインはこちら", main_posts_path %>
            </div>
        </div>
    </div>

    <div class="sympathy">
        <div class="sympathy__main">
            <h1>女性エンジニアの割合は低い。</h2>
            <img src="/assets/pcwomen.jpg" alt="women" />
            <p class="sympathy__text1">“もっと女性エンジニアと繋がりたい”</p>
            <p class="sympathy__text2">“周りに女性が少ないから不安”</p>
            <p class="sympathy__text3">“実際に女性エンジニアってどんな人がいるの？”</p>
        </div>
    </div>

    <div class="contents">
        <div class="contents__main">
            <img src="/assets/connect.jpg" alt="connect">
            <h1>Wcommunityとは...</h1>
            <p class="contents__text1">
                女性エンジニアやエンジニアを目指す女性が繋がる<br>
                コミュニケーションプラットフォームです。
            </p>
            <p class="contents__text2">
                現在、女性エンジニアの割合は２割と言われています。<br>
                もっとエンジニアを目指す女性が増えてほしい、<br>
                女性エンジニアが働きやすい環境になってほしい、<br>
                そういった想いからこのサービスは生まれました。
            </p>
        </div>
    </div>

    <div class="benefit">
        <div class="benefit__main">
            <div class="benefit__chat">
                <h2>チャットで繋がる</h2>
                <img src="/assets/chat.png" alt="chat" class="benefit__img">
            </div>
            <div class="benefit__map">
                <h2>マップで繋がる</h2>
                <img src="/assets/japanmap.png" alt="map" class="benefit__img">
            </div>
            <div class="benefit__post">
                <h2>投稿で繋がる</h2>
                <img src="/assets/post.png" alt="post" class="benefit__img">
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="logo">
        <span class="logo__w">W</span>
        <span class="logo__community">community</span>
    </div>
    <nav class="footer__nav">
        <ul class="footer__ul">
            <li class="footer__li"><a href="#">Top</a></li>
            <li class="footer__li"><a href="#">Service</a></li>
            <li class="footer__li"><%= link_to "LogIn", posts_path %></li>
        </ul>
        <div class="footer__copyright">&copy; Gankochan</div>
    </nav>
</footer>